spring.application.name=Dedicate Gateway
server.port=8080
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web.server=INFO
uri.workout-service=http://workout-service:8081/
uri.auth-service=http://auth-service:8010/


# Increase Circuit Breaker timeout to 5 seconds
resilience4j.circuitbreaker.instances.auth-CB.slowCallDurationThreshold=5000
resilience4j.circuitbreaker.instances.workout-CB.slowCallDurationThreshold=5000

# Increase the time window for the circuit breaker
resilience4j.timelimiter.instances.auth-CB.timeoutDuration=5s
resilience4j.timelimiter.instances.workout-CB.timeoutDuration=5s

server.forward-headers-strategy=none
