CREATE TABLE IF NOT EXISTS workout_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS workout_exercises (
    workout_template_id UUID NOT NULL REFERENCES workout_templates(id) ON DELETE CASCADE,
    exercise_order INTEGER NOT NULL,
    exercise_name VARCHAR(255) NOT NULL,
    goal_sets INTEGER NOT NULL,
    variant VARCHAR(255),
    PRIMARY KEY (workout_template_id, exercise_order)
);

CREATE TABLE IF NOT EXISTS workout_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workout_template_id UUID NOT NULL REFERENCES workout_templates(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exercise_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workout_entry_id UUID NOT NULL REFERENCES workout_entries(id) ON DELETE CASCADE,
    exercise_order INTEGER NOT NULL,
    exercise_name VARCHAR(255) NOT NULL,
    variant VARCHAR(255),
    goal_sets INTEGER,
    UNIQUE (workout_entry_id, exercise_order)
);

CREATE TABLE IF NOT EXISTS set_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    exercise_entry_id UUID NOT NULL REFERENCES exercise_entries(id) ON DELETE CASCADE,
    set_order INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight DOUBLE PRECISION,
    rpe DOUBLE PRECISION NOT NULL,
    notes VARCHAR(100),
    UNIQUE (exercise_entry_id, set_order)
);

CREATE TABLE IF NOT EXISTS exercise_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    equipment VARCHAR(255),
    variation VARCHAR(255),
    utility VARCHAR(255),
    mechanics VARCHAR(255),
    force VARCHAR(255),
    preparation TEXT,
    execution TEXT,
    target_muscles VARCHAR(255),
    synergist_muscles VARCHAR(255),
    stabilizer_muscles VARCHAR(255),
    antagonist_muscles VARCHAR(255),
    dynamic_stabilizer_muscles VARCHAR(255),
    main_muscle VARCHAR(255),
    difficulty INTEGER,
    secondary_muscles VARCHAR(255),
    parent_id BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exercise_info_name
    ON exercise_info(name);

CREATE TABLE IF NOT EXISTS splits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS split_workouts (
    split_id UUID NOT NULL REFERENCES splits(id) ON DELETE CASCADE,
    workout_template_id UUID NOT NULL REFERENCES workout_templates(id) ON DELETE CASCADE,
    workout_order INTEGER NOT NULL,
    PRIMARY KEY (split_id, workout_template_id)
);

CREATE INDEX IF NOT EXISTS idx_workout_templates_user_id
    ON workout_templates(user_id);

CREATE INDEX IF NOT EXISTS idx_workout_entries_user_id
    ON workout_entries(user_id);

CREATE INDEX IF NOT EXISTS idx_splits_user_id
    ON splits(user_id);
