CREATE TABLE IF NOT EXISTS exercise_catalog_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS exercise_catalog_utility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS exercise_catalog_mechanics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS exercise_catalog_force (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS exercise_catalog_difficulty (
    level INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS exercise_catalog_muscle_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS exercise_info_muscles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_info_id BIGINT NOT NULL REFERENCES exercise_info(id) ON DELETE CASCADE,
    muscle_role VARCHAR(32) NOT NULL,
    muscle_group_id BIGINT NOT NULL REFERENCES exercise_catalog_muscle_group(id) ON DELETE CASCADE,
    CONSTRAINT ck_exercise_info_muscles_role
        CHECK (muscle_role IN ('TARGET', 'SYNERGIST', 'STABILIZER', 'ANTAGONIST', 'DYNAMIC_STABILIZER', 'SECONDARY')),
    CONSTRAINT uq_exercise_info_muscles_identity
        UNIQUE (exercise_info_id, muscle_role, muscle_group_id)
);

ALTER TABLE exercise_info
    ADD COLUMN IF NOT EXISTS equipment_id BIGINT,
    ADD COLUMN IF NOT EXISTS utility_id BIGINT,
    ADD COLUMN IF NOT EXISTS mechanics_id BIGINT,
    ADD COLUMN IF NOT EXISTS force_id BIGINT,
    ADD COLUMN IF NOT EXISTS difficulty_id INTEGER,
    ADD COLUMN IF NOT EXISTS main_muscle_id BIGINT;

INSERT INTO exercise_catalog_equipment (name)
SELECT DISTINCT TRIM(equipment)
FROM exercise_info
WHERE equipment IS NOT NULL
  AND TRIM(equipment) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercise_catalog_utility (name)
SELECT DISTINCT TRIM(utility)
FROM exercise_info
WHERE utility IS NOT NULL
  AND TRIM(utility) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercise_catalog_mechanics (name)
SELECT DISTINCT TRIM(mechanics)
FROM exercise_info
WHERE mechanics IS NOT NULL
  AND TRIM(mechanics) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercise_catalog_force (name)
SELECT DISTINCT TRIM(force)
FROM exercise_info
WHERE force IS NOT NULL
  AND TRIM(force) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercise_catalog_difficulty (level)
SELECT DISTINCT difficulty
FROM exercise_info
WHERE difficulty IS NOT NULL
ON CONFLICT (level) DO NOTHING;

WITH muscle_tokens AS (
    SELECT
        LOWER(TRIM(token_text)) AS normalized_name,
        TRIM(token_text) AS muscle_name,
        ei.id AS source_id,
        token_row.ordinality AS token_ordinal
    FROM exercise_info ei
    CROSS JOIN LATERAL (
        VALUES
            (ei.main_muscle),
            (ei.target_muscles),
            (ei.synergist_muscles),
            (ei.stabilizer_muscles),
            (ei.antagonist_muscles),
            (ei.dynamic_stabilizer_muscles),
            (ei.secondary_muscles)
    ) AS source(raw_muscle)
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(source.raw_muscle, ''), ',') WITH ORDINALITY AS token_row(token_text, ordinality)
    WHERE TRIM(token_text) <> ''
      AND LOWER(TRIM(token_text)) <> 'none'
)
INSERT INTO exercise_catalog_muscle_group (name)
SELECT DISTINCT ON (normalized_name) muscle_name
FROM muscle_tokens
ORDER BY normalized_name, source_id, token_ordinal
ON CONFLICT (name) DO NOTHING;

UPDATE exercise_info ei
SET equipment_id = equipment_lookup.id
FROM exercise_catalog_equipment equipment_lookup
WHERE LOWER(TRIM(ei.equipment)) = LOWER(equipment_lookup.name);

UPDATE exercise_info ei
SET utility_id = utility_lookup.id
FROM exercise_catalog_utility utility_lookup
WHERE LOWER(TRIM(ei.utility)) = LOWER(utility_lookup.name);

UPDATE exercise_info ei
SET mechanics_id = mechanics_lookup.id
FROM exercise_catalog_mechanics mechanics_lookup
WHERE LOWER(TRIM(ei.mechanics)) = LOWER(mechanics_lookup.name);

UPDATE exercise_info ei
SET force_id = force_lookup.id
FROM exercise_catalog_force force_lookup
WHERE LOWER(TRIM(ei.force)) = LOWER(force_lookup.name);

UPDATE exercise_info ei
SET difficulty_id = difficulty_lookup.level
FROM exercise_catalog_difficulty difficulty_lookup
WHERE ei.difficulty = difficulty_lookup.level;

UPDATE exercise_info ei
SET main_muscle_id = muscle_lookup.id
FROM exercise_catalog_muscle_group muscle_lookup
WHERE LOWER(TRIM(ei.main_muscle)) = LOWER(muscle_lookup.name);

UPDATE exercise_info child
SET parent_id = parent_lookup.id
FROM exercise_info parent_lookup
WHERE child.parent_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM exercise_info existing_parent
      WHERE existing_parent.id = child.parent_id
  )
  AND parent_lookup.equipment_id = child.equipment_id
  AND LOWER(parent_lookup.name) = LOWER(
      regexp_replace(
          split_part(child.name, ':', 1),
          '\\s*\\(.*\\)\\s*$',
          '',
          'g'
      )
  )
  AND COALESCE(NULLIF(parent_lookup.variation, ''), 'No') = 'No';

INSERT INTO exercise_info_muscles (exercise_info_id, muscle_role, muscle_group_id)
WITH muscle_rows AS (
    SELECT ei.id AS exercise_info_id, 'TARGET' AS muscle_role, TRIM(token) AS muscle_name
    FROM exercise_info ei
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ei.target_muscles, ''), ',') AS token
    WHERE TRIM(token) <> ''
      AND LOWER(TRIM(token)) <> 'none'
    UNION ALL
    SELECT ei.id, 'SYNERGIST', TRIM(token)
    FROM exercise_info ei
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ei.synergist_muscles, ''), ',') AS token
    WHERE TRIM(token) <> ''
      AND LOWER(TRIM(token)) <> 'none'
    UNION ALL
    SELECT ei.id, 'STABILIZER', TRIM(token)
    FROM exercise_info ei
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ei.stabilizer_muscles, ''), ',') AS token
    WHERE TRIM(token) <> ''
      AND LOWER(TRIM(token)) <> 'none'
    UNION ALL
    SELECT ei.id, 'ANTAGONIST', TRIM(token)
    FROM exercise_info ei
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ei.antagonist_muscles, ''), ',') AS token
    WHERE TRIM(token) <> ''
      AND LOWER(TRIM(token)) <> 'none'
    UNION ALL
    SELECT ei.id, 'DYNAMIC_STABILIZER', TRIM(token)
    FROM exercise_info ei
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ei.dynamic_stabilizer_muscles, ''), ',') AS token
    WHERE TRIM(token) <> ''
      AND LOWER(TRIM(token)) <> 'none'
    UNION ALL
    SELECT ei.id, 'SECONDARY', TRIM(token)
    FROM exercise_info ei
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ei.secondary_muscles, ''), ',') AS token
    WHERE TRIM(token) <> ''
      AND LOWER(TRIM(token)) <> 'none'
)
SELECT
    muscle_rows.exercise_info_id,
    muscle_rows.muscle_role,
    muscle_lookup.id
FROM muscle_rows
JOIN exercise_catalog_muscle_group muscle_lookup
    ON LOWER(muscle_rows.muscle_name) = LOWER(muscle_lookup.name)
ON CONFLICT (exercise_info_id, muscle_role, muscle_group_id) DO NOTHING;

ALTER TABLE exercise_info
    ADD CONSTRAINT fk_exercise_info_equipment_id
        FOREIGN KEY (equipment_id) REFERENCES exercise_catalog_equipment(id),
    ADD CONSTRAINT fk_exercise_info_utility_id
        FOREIGN KEY (utility_id) REFERENCES exercise_catalog_utility(id),
    ADD CONSTRAINT fk_exercise_info_mechanics_id
        FOREIGN KEY (mechanics_id) REFERENCES exercise_catalog_mechanics(id),
    ADD CONSTRAINT fk_exercise_info_force_id
        FOREIGN KEY (force_id) REFERENCES exercise_catalog_force(id),
    ADD CONSTRAINT fk_exercise_info_difficulty_id
        FOREIGN KEY (difficulty_id) REFERENCES exercise_catalog_difficulty(level),
    ADD CONSTRAINT fk_exercise_info_main_muscle_id
        FOREIGN KEY (main_muscle_id) REFERENCES exercise_catalog_muscle_group(id),
    ADD CONSTRAINT fk_exercise_info_parent_id
        FOREIGN KEY (parent_id) REFERENCES exercise_info(id) ON DELETE SET NULL;

ALTER TABLE exercise_info
    ALTER COLUMN equipment_id SET NOT NULL,
    ALTER COLUMN utility_id SET NOT NULL,
    ALTER COLUMN mechanics_id SET NOT NULL,
    ALTER COLUMN force_id SET NOT NULL,
    ALTER COLUMN difficulty_id SET NOT NULL,
    ALTER COLUMN main_muscle_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_exercise_info_equipment_id
    ON exercise_info(equipment_id);

CREATE INDEX IF NOT EXISTS idx_exercise_info_utility_id
    ON exercise_info(utility_id);

CREATE INDEX IF NOT EXISTS idx_exercise_info_mechanics_id
    ON exercise_info(mechanics_id);

CREATE INDEX IF NOT EXISTS idx_exercise_info_force_id
    ON exercise_info(force_id);

CREATE INDEX IF NOT EXISTS idx_exercise_info_difficulty_id
    ON exercise_info(difficulty_id);

CREATE INDEX IF NOT EXISTS idx_exercise_info_main_muscle_id
    ON exercise_info(main_muscle_id);

CREATE INDEX IF NOT EXISTS idx_exercise_info_muscles_role_group
    ON exercise_info_muscles(muscle_role, muscle_group_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exercise_info_identity
    ON exercise_info (LOWER(name), LOWER(COALESCE(variation, '')), equipment_id);

ALTER TABLE exercise_info
    DROP COLUMN IF EXISTS equipment,
    DROP COLUMN IF EXISTS utility,
    DROP COLUMN IF EXISTS mechanics,
    DROP COLUMN IF EXISTS force,
    DROP COLUMN IF EXISTS target_muscles,
    DROP COLUMN IF EXISTS synergist_muscles,
    DROP COLUMN IF EXISTS stabilizer_muscles,
    DROP COLUMN IF EXISTS antagonist_muscles,
    DROP COLUMN IF EXISTS dynamic_stabilizer_muscles,
    DROP COLUMN IF EXISTS main_muscle,
    DROP COLUMN IF EXISTS difficulty,
    DROP COLUMN IF EXISTS secondary_muscles;
