ALTER TABLE workout_entries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE workout_templates ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE exercise_configs ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE set_entries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE workout_entries ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE workout_templates ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE exercise_configs ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE exercise_configs ADD COLUMN updated_at TIMESTAMP;
